import type { Plugin } from 'vite'
import { resolve } from 'node:path'
const components = {
  "registerXChartAnalyticsModules": "src/components/display-components/chart",
  "XBaseInput": "src/components/basic-components/base-input",
  "XBrick": "src/components/basic-components/brick",
  "XBrickItem": "src/components/basic-components/brick",
  "XButton": "src/components/basic-components/button",
  "XButtonGroup": "src/components/basic-components/button-group",
  "XCard": "src/components/basic-components/card",
  "XDivider": "src/components/basic-components/divider",
  "XFlow": "src/components/basic-components/flow",
  "XFlowItem": "src/components/basic-components/flow",
  "XGrid": "src/components/basic-components/grid",
  "XGridItem": "src/components/basic-components/grid",
  "XGroupContainer": "src/components/basic-components/group-container",
  "XIcon": "src/components/basic-components/icon",
  "XLayout": "src/components/basic-components/layout",
  "XScrollbar": "src/components/basic-components/scrollbar",
  "XSplitPane": "src/components/basic-components/splitter",
  "XSplitter": "src/components/basic-components/splitter",
  "XText": "src/components/basic-components/text",
  "XAvatar": "src/components/display-components/avatar",
  "XChat": "src/components/display-components/chat",
  "XBadge": "src/components/display-components/badge",
  "XChart": "src/components/display-components/chart",
  "XCollapse": "src/components/display-components/collapse",
  "XDescriptions": "src/components/display-components/descriptions",
  "XEmpty": "src/components/display-components/empty",
  "XList": "src/components/display-components/list",
  "XProgress": "src/components/display-components/progress",
  "XScrollingText": "src/components/display-components/scrolling-text",
  "XSkeleton": "src/components/display-components/skeleton",
  "XStatistic": "src/components/display-components/statistic",
  "XTable": "src/components/display-components/table",
  "XTag": "src/components/display-components/tag",
  "XTree": "src/components/display-components/tree",
  "XTreeTable": "src/components/display-components/tree-table",
  "XAlert": "src/components/feedback-components/alert",
  "XDialog": "src/components/feedback-components/dialog",
  "XDrawer": "src/components/feedback-components/drawer",
  "XLoading": "src/components/feedback-components/loading",
  "XMessage": "src/components/feedback-components/message",
  "XMessageBox": "src/components/feedback-components/message-box",
  "XNotification": "src/components/feedback-components/notification",
  "XPopconfirm": "src/components/feedback-components/popconfirm",
  "XPopover": "src/components/feedback-components/popover",
  "XTooltip": "src/components/feedback-components/tooltip",
  "XAutocomplete": "src/components/form-components/autocomplete",
  "XCascader": "src/components/form-components/cascader",
  "XCheckbox": "src/components/form-components/checkbox",
  "XColorPicker": "src/components/form-components/color-picker",
  "XColorPickerPanel": "src/components/form-components/color-picker-panel",
  "XDatePicker": "src/components/form-components/date-picker",
  "XDatePickerPanel": "src/components/form-components/date-picker-panel",
  "XDateTimePicker": "src/components/form-components/date-time-picker",
  "XForm": "src/components/form-components/form",
  "XFormItem": "src/components/form-components/form",
  "XIconSelect": "src/components/form-components/icon-select",
  "XInput": "src/components/form-components/input",
  "XInputNumber": "src/components/form-components/input-number",
  "XRadio": "src/components/form-components/radio",
  "XRadioButton": "src/components/form-components/radio",
  "XOption": "src/components/form-components/select",
  "XSelect": "src/components/form-components/select",
  "XSlider": "src/components/form-components/slider",
  "XSwitch": "src/components/form-components/switch",
  "XTextarea": "src/components/form-components/textarea",
  "XTimePicker": "src/components/form-components/time-picker",
  "XTimeSelect": "src/components/form-components/time-select",
  "XUpload": "src/components/form-components/upload",
  "XBreadcrumb": "src/components/navigation-components/breadcrumb",
  "XDropdown": "src/components/navigation-components/dropdown",
  "XDropdownItem": "src/components/navigation-components/dropdown-item",
  "XDropdownMenu": "src/components/navigation-components/dropdown-menu",
  "XFloatButtonGroup": "src/components/navigation-components/float-button-group",
  "XHorizontalMenu": "src/components/navigation-components/nav-menu",
  "XNavMenu": "src/components/navigation-components/nav-menu",
  "XVerticalMenu": "src/components/navigation-components/nav-menu",
  "XPagination": "src/components/navigation-components/pagination",
  "XSteps": "src/components/navigation-components/steps",
  "XTabs": "src/components/navigation-components/tabs",
  "XTools": "src/components/navigation-components/tools",
  "XUserStatus": "src/components/navigation-components/user-status",
  "XDataTableSettings": "src/components/other-components/data-table-settings",
  "XFileDisk": "src/components/other-components/file-disk",
  "XJsonEditor": "src/components/other-components/json-editor",
  "XLogin": "src/components/other-components/login",
  "XLoginPage": "src/components/other-components/login-page",
  "XRegister": "src/components/other-components/register",
  "XRichTextEditor": "src/components/other-components/rich-text-editor",
  "XTableColumnSettings": "src/components/other-components/table-column-settings",
  "XLoadingService": "src/components/feedback-components/loading",
  "XMessageComponent": "src/components/feedback-components/message",
  "XMessageBoxComponent": "src/components/feedback-components/message-box",
  "XNotificationComponent": "src/components/feedback-components/notification"
}
export function exampleImports(): Plugin {
  return { name: 'x-ui-example-imports', enforce: 'pre', transform(code, id) {
    if (!id.replace(/\\/g, '/').includes('/docs/examples/') || !id.endsWith('.vue')) return
    return code.replace(/import\s*\{([^}]+)\}\s*from\s*['"]@x-soft88\/x-ui['"]/g, (_, names: string) => {
      const groups = new Map<string, string[]>()
      for (const binding of names.split(',')) {
        const name = binding.trim().replace(/^type\s+/, '').split(/\s+as\s+/)[0]
        const folder = components[name as keyof typeof components] ?? 'src/components'
        const list = groups.get(folder) ?? []; list.push(binding.trim()); groups.set(folder, list)
      }
      return [...groups].map(([folder, bindings]) => 'import { ' + bindings.join(', ') + ' } from ' + JSON.stringify(resolve(folder))).join('\n')
    }).split("'@x-soft88/x-ui/style.css'").join(JSON.stringify(resolve('src/styles/index.css')))
  } }
}
